name: gocial
services:
  web:
    image: nginx:1.25
    volumes:
      - type: bind
        source: ./nginx/nginx.conf
        target: /etc/nginx/conf.d/default.conf
        read_only: true
    ports:
      - 80:80
  backend:
    build:
      context: backend
    ports:
      - 8080:8080
  frontend:
    build: frontend
    ports:
      - 3000:3000